---

- name: Converge
  hosts: one
  tasks:
    - name: "Test haxwithaxe.etc_hosts defaults"
      include_role:
        name: "haxwithaxe.etc_hosts"
      vars:
        # Can't fiddle with /etc/hosts in docker so this isn't default
        etc_hosts_path: /tmp/hosts
