---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-one
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    groups:
      - one
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance-one:
        etc_hosts_address: "9.8.7.6"
        etc_hosts_list:
          - name: instance-many0
            address: "1.2.3.4"
          - name: instance-many1
            address: "5.6.7.8"
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
