---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-one
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    groups:
      - one
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
