---

- name: Converge
  hosts: one
  tasks:
    - name: "Test haxwithaxe.etc_hosts defaults"
      include_role:
        name: "haxwithaxe.etc_hosts"
      vars:
        etc_hosts_path: /tmp/hosts
        etc_hosts_suffix: .suffix
